site_name: "NB Defense: Secure Jupyter Notebooks"

repo_name: protectai/nbdefense
repo_url: https://github.com/protectai/nbdefense
edit_uri: ""

copyright: Copyright &copy; 2023

theme:
  name: material
  home: home.html
  custom_dir: overrides
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/imgs/top-logo.svg
  favicon: assets/imgs/favicon.svg

extra_css:
  - assets/css/extra.css

nav:
  - Home: "index.md"
  - "Getting Started":
    - "getting-started/index.md"
    - "CLI": "getting-started/cli.md"
    - "JupyterLab Extension": "getting-started/jupyter-lab-extension.md"
    - "JupyterLab Extension on Cloud Services":
        - "getting-started/cloud-services/index.md"
        - "SageMaker Notebook Instances": "getting-started/cloud-services/sage-maker-notebook-instances.md"
        - "Sage Maker Studio Lab": "getting-started/cloud-services/sage-maker-studio-lab.md"
        - "Azure ML Notebooks": "getting-started/cloud-services/azure-ml-notebooks.md"
        - "SageMaker Studio - COMING SOON": "getting-started/cloud-services/sage-maker-studio.md"
  - "Supported Scans":
      - "Secrets Detection": "supported-scans/detecting-secrets.md"
      - "PII Detection": "supported-scans/detecting-PII.md"
      - "CVE Detection": "supported-scans/detecting-CVEs.md"
      - "License Detection": "supported-scans/detecting-licenses.md"
  - "Scan Settings":
      - "scan-settings/index.md"
      - "JupyterLab Extension Settings": "scan-settings/jupyterlab-settings.md"
      - "CLI Settings": "scan-settings/cli-settings.md"
      - "CLI Flags": "scan-settings/cli-flags.md"
  - "FAQ": 
    - "FAQ": "faq.md"
  - "About Us": "about-us.md"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - lightgallery
  - admonition

plugins:
  - search
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 10
      max_length: 160

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/protectai/nbdefense
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/protect-ai/
    - icon: fontawesome/brands/slack
      link: https://mlsecops.slack.com
    - icon: social-discussion
      link: https://github.com/protectai/nbdefense/discussions
  generator: false
